/**
 * Created by lyuwei on 2018/1/1.
 */
Ext.define('yt.view.monpot.timeline.TimeLineModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.timeline',

    stores: {
        /*
        A declaration of Ext.data.Store configurations that are first processed as binds to produce an effective
        store configuration. For example:

        users: {
            model: 'TimeLine',
            autoLoad: true
        }
        */
        deviceWarning:  {
            fields: [
                { name: 'deviceid' },
                { name: 'quakeid' },
                { name: 'devicename' },
                { name: 'quakename' },
                { name: 'alarmtype' },
                { name: 'settingv' },
                { name: 'alarmv' },
                { name: 'rank' },
                { name: 'deleteflag' },
                { name: 'status' },
                { name: 'content' },
                { name: 'alarmtime', type: 'date' },
                { name: 'addtime', type: 'date' },
                { name: 'modtime', type: 'date' }
            ],
            sorters: {
                property: 'alarmtime',
                direction: 'DESC'
            },
            data: [
                {
                    "id": 3,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 3,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.3mm",
                    "alarmtime": "2017-12-11 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 2,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 2,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.3mm",
                    "alarmtime": "2017-12-19 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 1,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.3mm",
                    "alarmtime": "2017-12-10 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 6,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-18 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 7,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-12 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 13,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-19 16:15:03",
                    "addtime": "2017-12-19 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 15,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-19 16:15:03",
                    "addtime": "2017-12-19 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 14,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-19 16:15:03",
                    "addtime": "2017-12-19 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 5,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-18 16:15:03",
                    "addtime": "2017-12-18 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 9,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-17 16:15:03",
                    "addtime": "2017-12-17 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 10,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-17 16:15:03",
                    "addtime": "2017-12-17 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 11,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-17 16:15:03",
                    "addtime": "2017-12-17 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 12,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 2,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-17 16:15:03",
                    "addtime": "2017-12-17 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 4,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 43,
                    "alarmv": 24,
                    "rank": 4,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-12 16:15:03",
                    "addtime": "2017-12-12 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 8,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-12 16:15:03",
                    "addtime": "2017-12-12 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                }
            ]
        }
    },

    data:{

    }
});