/**
 * Created by lyuwei on 2018/1/1.
 */
Ext.define('yt.view.monpot.timeline.TimeLineModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.timeline',

    data: {
        quakeInfo: {
            "id": 1,
            "quakeid": 100007,
            "regionid": 500000000,
            "name": "贵溪市煤矿",
            "company": "鹰潭市国土资源局",
            "favostatus": 1,
            "status": 0,
            "username": "秦晨光",
            "mobile": "18826376263",
            "description": "该地灾点的险情等级很高，威胁人数很多，需要重点监测。",
            "note": "鹰潭市为地质灾害防治制定发布了《鹰潭市地质灾害防治方案》和《突发性地质灾害应急预案》并将此预案列入了鹰潭市突发公共事件总体应急预案。由于人工测量并不能对采空区进行全天候监测，要求实现自动化监测。该项目通过对贵溪市石膏矿采空塌陷区安装监测设备，对主要技术数据的实时监测监控，巡线员数据的实时查询，监测数据的智能分析等。实时了解该采空区安全状态并做出预测预警，为科学决策提供依据。",
            "attr": "[{\"lng\":\"117.202892\",\"lat\":\"28.220454\"},{\"lng\":\"117.202889\",\"lat\":\"28.220454\"},{\"lng\":\"117.202889\",\"lat\":\"28.220454\"},{\"lng\":\"117.202889\",\"lat\":\"28.220321\"}]",
            "centroid": "{\"lat\":\"28.220454\",\"lng\":\"117.202892\"}",
            "image": "[\"http://yt.qinchenguang.com/img/1.png\",\"http://yt.qinchenguang.com/img/2.png\"]",
            "createtime": "2017-11-30 17:36:26",
            "modifytime": "2017-11-30 17:36:26",
            "rank": 0,
            "typenum": 2,
            "devicenum": 3,
            "alarmnum": 0,
            "dtype": "地面塌陷",
            "address": "南山大道与火炬大道交叉口东50米",
            "dlevel": "大型",
            "dnum": 11,
            "davoid": "监测、避让、巡查",
            "dmethod": "口哨、铜锣",
            "daddress": "村委会、投亲戚家、邻居",
            "droute": "村前公路"
        }
    },

    stores: {
        /*
        A declaration of Ext.data.Store configurations that are first processed as binds to produce an effective
        store configuration. For example:

        users: {
            model: 'TimeLine',
            autoLoad: true
        }
        */
        deviceWarning:  {
            fields: [
                { name: 'deviceid' },
                { name: 'quakeid' },
                { name: 'devicename' },
                { name: 'quakename' },
                { name: 'alarmtype' },
                { name: 'settingv' },
                { name: 'alarmv' },
                { name: 'rank', type: 'number' },
                { name: 'deleteflag' },
                { name: 'status' },
                { name: 'content' },
                { name: 'alarmtime', type: 'date' },
                { name: 'addtime', type: 'date' },
                { name: 'modtime', type: 'date' }
            ],
            sorters: {
                property: 'alarmtime',
                direction: 'DESC'
            },
            data: [
                {
                    "id": 3,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 3,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.3mm",
                    "alarmtime": "2017-12-11 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 2,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 2,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.3mm",
                    "alarmtime": "2017-12-19 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 1,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.3mm",
                    "alarmtime": "2017-12-10 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 6,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-18 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 7,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-12 16:15:03",
                    "addtime": "2017-12-20 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 13,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-19 16:15:03",
                    "addtime": "2017-12-19 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 15,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-19 16:15:03",
                    "addtime": "2017-12-19 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 14,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-19 16:15:03",
                    "addtime": "2017-12-19 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 5,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-18 16:15:03",
                    "addtime": "2017-12-18 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 9,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-17 16:15:03",
                    "addtime": "2017-12-17 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 10,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-17 16:15:03",
                    "addtime": "2017-12-17 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 11,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-17 16:15:03",
                    "addtime": "2017-12-17 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 12,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 2,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过1.3mm",
                    "alarmtime": "2017-12-17 16:15:03",
                    "addtime": "2017-12-17 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 4,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 43,
                    "alarmv": 24,
                    "rank": 4,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-12 16:15:03",
                    "addtime": "2017-12-12 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                },
                {
                    "id": 8,
                    "deviceid": 302,
                    "quakeid": 100000,
                    "devicename": "裂缝监测设备1",
                    "quakename": "贵溪市石膏矿",
                    "alarmtype": "x",
                    "settingv": 23,
                    "alarmv": 24,
                    "rank": 1,
                    "deleteflag": 0,
                    "status": 0,
                    "content": "单位时间内裂缝超过0.4mm",
                    "alarmtime": "2017-12-12 16:15:03",
                    "addtime": "2017-12-12 16:15:03",
                    "modtime": "2017-11-26 21:13:13"
                }
            ]
        }
    }
});